### ISSUE TITLE
Add support of self referencing loop

### ISSUE THREAD

**Issue by antonovicha** [theramis/Snapper#100]
**Is your feature request related to a problem? Please describe.**
Currently testing of EF Entities is not smooth because navigation properties create reference loops.

**Describe the solution you'd like**
Add support to configure self reference loop. May be expose Newtonsoft Json config as parameter to ShouldMatchSnapshot()?

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by theramis** [comment]
Awesome timing, I'm working on introducing this atm. I should have something out in the next 2 weeks or so which should allow this :)

**Comment by theramis** [comment]
Just added Custom Snapshot Settings in the latest version [2.4.0](https://www.nuget.org/packages/Snapper/2.4.0). See the docs [here](https://theramis.github.io/Snapper/#/pages/snapper/custom_snapshot_settings). 

That should hopefully solve your issue?

**Comment by theramis** [comment]
Closing as its been a while with no response.
