### ISSUE TITLE
Snapper.Json.Xunit does not work in Release builds

### ISSUE THREAD

**Issue by PatrickLehnerXI** [theramis/Snapper#16]
(This is based on Snapper v1.3.1)

Since the XUnit integration uses StackTraces to find information about the test that is actually using it (see [`XUnitHelper.GetCallingTestInfo()`](https://github.com/theramis/Snapper/blob/bd0775feac230e32698a2f9cfda074250bea7413/Snapper.Json.Xunit/XUnitTestHelper.cs#L12)), this cannot be used in "release" builds (i.e. any release that does not include debug symbols and/or uses extensive optimization).

As [the "Remarks" section on the `StackTrace` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stacktrace?#remarks) states:

> `StackTrace` information will be most informative with Debug build configurations. By default, Debug builds include debug symbols, while Release builds do not. The debug symbols contain most of the file, method name, line number, and column information used in constructing `StackFrame` and `StackTrace` objects.
> 
> `StackTrace` might not report as many method calls as expected, due to code transformations that occur during optimization.

Running tests in a release configuration might not be the default use case, but I think it's not very unusual either. Especially in CI servers, where you want to test what you deploy, building and testing the release configuration seems valid to me. (This is, in fact, how this issue bit me.)

It would be great if future versions of Snapper could use more robust ways to automatically gather the information that XUnitSnapper so conveniently provides.

A possible alternative might be the ["caller information"](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information) attributes where the compiler fills in certain information about the source file containing the call site, in particular [`[CallerMemberName]`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute) and [`[CallerFilePath]`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerfilepathattribute).

If release configuration cannot be supported (e.g. too much effort, or technically not feasible in general), it would be great if you could at least specify this as a known limitation in a prominent place (e.g. the README file).

Thanks for the work you put into this library already! It makes snapshot test really quite convenient :)

**Comment by PatrickLehnerXI** [comment]
To illustrate, here are two overloads for a replacement `MatchSnapshot` method providing the same functionality as XUnitSnapper (though by using JsonSnapper publicly, not as a subclass):

```cs
/// <summary>
/// Compare the given object with its snapshot, and fail the test if they are not equal.
/// Uses the member name of the calling function as the snapshot name.
/// </summary>
/// <seealso cref="MatchSnapshot(string,object,string)"/>
/// <param name="value">object to compare to snapshot.</param>
/// <param name="memberName">name of calling member; auto-filled by compiler.</param>
/// <param name="sourceFilePath">source file path of call site; auto-filled by compiler.</param>
public static void MatchSnapshot(
    object value,
    [CallerMemberName] string memberName = "",
    [CallerFilePath] string sourceFilePath = "")
{
    MatchSnapshot(memberName, value, sourceFilePath);
}

/// <summary>
/// Compare the given object with its snapshot at the given snapshot name, and fail the test if they are not equal.
/// </summary>
/// <param name="snapshotName">name of the snapshot (without snapshot file extension).</param>
/// <param name="value">object to compare to snapshot.</param>
/// <param name="sourceFilePath">source file path of call site; auto-filled by compiler.</param>
public static void MatchSnapshot(
    string snapshotName,
    object value,
    [CallerFilePath] string sourceFilePath = "")
{
    var snapshotDirectory = Path.Join(Path.GetDirectoryName(sourceFilePath), SnapshotSubfolder);
    var jsonSnapper = new JsonSnapper(new XUnitAsserter(), "_snapshots");
    jsonSnapper.Snap(snapshotName + ".json", value);
}
```

**Comment by theramis** [comment]
Hey @PatrickLehnerXI, 

I've recently encountered this exact issue while working in Snapper v2. This basically happens because of method inlining which the compiler does. 
Here is a nice explanation of what that means https://stackoverflow.com/questions/3924995/what-is-method-inlining

Due to the nature of the issue, this only happens when the main test method is very small. I found that this doesn't happen too much in practice so I've made an assumption that this issue is an edge case. (Please let me know if you disagree)


Anyhow there were three solutions that I found for this issue.
1. Set the following attribute on the test method `[MethodImpl(MethodImplOptions.NoInlining)]` as seen [here](https://github.com/theramis/Snapper/blob/516598b41426fcfd0968db170dcd805e30604cbb/project/Tests/Snapper.Tests/SnapperSnapshotsPerClassTests.cs#L13).
2. Disable optimisation of code for your release builds of your test project. You can do this by adding this into your projects csproj file. 
```
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <Optimize>false</Optimize>
</PropertyGroup>
```
3. As you suggested above to use caller information methods. 


In my opinion option 3 would be the best since it requires no change from the user of the library. Unfortunately I'm not a fan of providing the user an optional parameter which they have to ignore. 
Assuming this issue is an edge case I feel like both option 1 and 2 would be good enough for users. If it ends up being a much bigger issue than I assume I'd be happy to re-evaluate. 

I'll update the readme in the weekend and if you are happy I shall close the issue after that 😄

**Comment by PatrickLehnerXI** [comment]
Hey @theramis, thanks for getting back to me so quickly.

> Due to the nature of the issue, this only happens when the main test method is very small. I found that this doesn't happen too much in practice so I've made an assumption that this issue is an edge case. (Please let me know if you disagree)

I would in fact disagree here -- small test cases are not that unusual, and IMO are quite justified for unit tests.

In addition, since the compiler decides what is "small" in this case (i.e. when the method gets inlined), this may change between compiler versions (particularly relevant when working with DotNet Core, as we do). So a test (that doesn't use the `[MethodImpl(MethodImplOptions.NoInlining)]` attribute) that works one day may break after a compiler update.

I do see your point with the optional parameters that aren't actually optional, but I think in this particular case,  it's easy enough to show users the correct usage with some examples. So my preferred way would indeed be that Snapper implements option 3 at some point.

However, what bothered me most about this was the surprising occurrence of this limitation; so adding this to the readme would suffice for now IMO, so you can close this issue :)

FWIW, in our project we're using a small static helper with the alternative `MatchSnapshot` methods that I posted above, and don't use `XUnitSnapper` directly.

**Comment by theramis** [comment]
Update readme to include this issue https://github.com/theramis/Snapper/blob/master/README.md#faqs . 

I'll leave this issue open until v2 is out and its decided how v2 will handle this issue.

**Comment by ViceIce** [comment]
A solution could be to include a `props` file to the package, with will set the `Optimize` flag to `false`

**Comment by theramis** [comment]
Decided to not do anything for now. 
Snapper throws a better error which lets the user know why it's failing. 

Its also mentioned in the FAQS on how they can solve the issue. 
https://theramis.github.io/Snapper/FAQS.html
