### ISSUE TITLE
(feature) Support net45

### ISSUE THREAD

**Issue by ViceIce** [theramis/Snapper#18]
We would like to use Snapper but we are limited to net45 /net452.

I've made a small diff to add this support. I can also send a pr if you like that idea.

[snapper.txt](https://github.com/theramis/Snapper/files/3165781/snapper.txt)

**Comment by ViceIce** [comment]
[gist](https://gist.github.com/ViceIce/cefdc272b33f23914d038f7abe263844)

**Comment by theramis** [comment]
Hey @ViceIce 
I'm currently working on V2 of Snapper which is in this branch https://github.com/theramis/Snapper/tree/v2. There is a nuget package for it as well here https://www.nuget.org/packages/Snapper . 


Unfortunately V2 currently doesn't support .net 45 either. 

Could you perhaps try and see if you can make the code in v2 work with .net45? 

Unfortunately the current version in master will be deprecated in the next month or so.

**Comment by ViceIce** [comment]
Sure, i can send two pr. one with the current fix to support net45 until v2 is ready and another one for the v2 fixes.

ok?

**Comment by theramis** [comment]
> Sure, i can send two pr. one with the current fix to support net45 until v2 is ready and another one for the v2 fixes.

That would be awesome!

**Comment by theramis** [comment]
@ViceIce just had a thought. 
If you are happy with using the beta version of V2, you could just make the changes for V2 and save yourself some extra work. I'll be releasing the beta version in the next 2 days.

**Comment by ViceIce** [comment]
the fix for the current master is ready, see above gist. i only have to fork your repo, push my local commit and open pr 😄

**Comment by ViceIce** [comment]
done :tada:

**Comment by ViceIce** [comment]
why you don't run all tests with appveyor logger?

**Comment by theramis** [comment]
> done

Yay thanks a lot. Just has one comment. Once that resolved, I'll merge and deploy tomorrow sometime. (Super late in my timezone)

> why you don't run all tests with appveyor logger?

Originally only added to the Nunit tests because the nunit runner has some issues. I might add it to all now though to make life easier.

**Comment by ViceIce** [comment]
no problem, fixed the issues.

here in germany we have early afternoon :smile:

**Comment by theramis** [comment]
Changes merged and released in version 1.4.0. 

The changes for V2 should be released today/tomorrow in the 2.0.0-beta.
