### ISSUE TITLE
sign assemblies

### ISSUE THREAD

**Issue by ViceIce** [theramis/Snapper#22]
We have a project (net45) where signed assemblies are a hard requirement. They got installed to the global assembly cache.

Can we sign the Snapper assemblies? I can send a pr.

**Comment by theramis** [comment]
Hmm, I've had a look at your PR and it looks fine. 
Although I don't know much about strong naming assemblies and from some quick googling I would like to know much more about it before I commit to it. 

Unfortunately I won't get enough time during the week to look into this. I'll follow up on this in the weekend.

**Comment by ViceIce** [comment]
Ok, additionally i would suggest to use [minver]8https://github.com/adamralph/minver#readme) for automated versioning.

When we use assembly signing, assemblies are linked by assembly name, version and publickeytoken. Without signing, only the assembly name is used. so to left assemblies compatible (without require redirects) we should set the assembly version to only the majoversion. all other part should be zero.
`MinVer` will do that for you while build.

**Comment by ViceIce** [comment]
Any news?

**Comment by theramis** [comment]
> Any news?

Hey sorry, I didn't end up getting time last weekend. I should have free time this weekend and I'll have a look into it. 

> Ok, additionally i would suggest to use minver for automated versioning.

That looks great, I'll look into it aswell. Thanks

**Comment by theramis** [comment]
Made the changes. 
Deployed in `Snapper 2.0.0-beta3`!

**Comment by ViceIce** [comment]
Works, thanks
