### ISSUE TITLE
Feature Request: when update snapshot is on test should be Inconclusive/Fail

### ISSUE THREAD

**Issue by timker** [theramis/Snapper#26]
FYI, I haven't updated from Snapper 1 yet.

I'm worried that an inexperienced Developer may commit 
[assembly: UpdateSnapshots]
Then test would always pass.

Making the Test inconclusive... or outright failing would stop any mistakes

**Comment by theramis** [comment]
Hey @timker, 

Thanks for making the issue. 

As you probably already know in Snapper V2, having the `[assembly: UpdateSnapshots]` attribute during supported CI builds would be ignored. 

Adding this functionality into Snapper v1 wouldn't be a super simple task and considering Snapper v1 is deprecated I don't think it would be a good idea to add it there. 
I'd suggest upgrading to V2 as soon as possible.

**Comment by timker** [comment]
ahh cool, I didn't know that CI would ignore it

FYI I wasn't asking to port that feature to 1.0, was just curious about ways to stop devs messing up .

Thanks for the reply

**Comment by theramis** [comment]
> ahh cool, I didn't know that CI would ignore it
> 
> FYI I wasn't asking to port that feature to 1.0, was just curious about ways to stop devs messing up .
> 
> Thanks for the reply

Ahh sorry, my bad. I interpreted it incorrectly. 
I had the same issue with V1 and therefore in V2 made it redundant.
