### ISSUE TITLE
NUnit support

### ISSUE THREAD

**Issue by fgather** [theramis/Snapper#3]
Hi,

Thanks for you great work! 
I'm currently trying to extend Snapper to support NUnit. Are you interested in a PR? Or should I create it as a standalone package? If you'd like having it here in your code base, would you mind me moving some stuff from the XUnit implementation which is common to both Testrunners? Also I'd slightly change the SnapperCore interface to allow for easier support of NUnit style constraints. 
In case you don't want to natively support NUnit, which would be perfectly fine, I'd release it as a standalone Nuget Package which would depend on Snapper, if you're fine with it.

**Comment by theramis** [comment]
Hey @fgather, 
I'd be happy to include support for NUnit. 

A PR would be great if you have time!

Your changes sound reasonable to me. Send through the PR and we can talk about it more there 😄

**Comment by fgather** [comment]
I created a PR for it: https://github.com/theramis/Snapper/pull/4

**Comment by theramis** [comment]
PR has been merged. 
See https://github.com/theramis/Snapper/pull/4#issuecomment-455089486 for more details on when Nunit support will be out

**Comment by theramis** [comment]
Released [Snapper.Json.Nunit v1.3.1](https://www.nuget.org/packages/Snapper.Json.Nunit/1.3.1) on nuget!

Thanks for your help @fgather!

Closing this issue 😄

**Comment by theramis** [comment]
@all-contributors please @fgather for ideas
