### ISSUE TITLE
DateTimeOffset property gives false positive

### ISSUE THREAD

**Issue by plitwinski** [theramis/Snapper#44]
At work I'm using snapper quite extensively for api contract testing and found a little bit of a problem when trying to assert against a snapshot that contains `DateTimeOffset` properties.

After a little bit of digging it looks like it's related to `Newtonsoft.Json`  issue reported here https://github.com/JamesNK/Newtonsoft.Json/issues/1110

Given that it's not exactly a bug (as it's expected behavior from `Newtonsoft.Json` I thought a slight change that would allow to configure stored snapshot deserialisation behaviour would be nice.

Usually code is much easier to follow that words, I put together a PR that addresses the issue ( https://github.com/theramis/Snapper/pull/43 ).

Alternatively, `JsonSerializerSettings` could be passed as a parameter to `ShouldMatchSnapshot` method but guess it might make it a little bit more convoluted.

Having something like that would really make my life easier as currently whole snapshot needs to be stored as a string to workaround the issue....

What do you think about this proposal?

**Comment by theramis** [comment]
Hey @plitwinski, 

Thanks for making the issue. I've replied to your PR and I've also just made a new PR with the fix. 
Would you mind testing your code with this PR and checking if it works? 
https://github.com/theramis/Snapper/pull/45

If you need I can create a beta version of the nuget package for testing.

**Comment by plitwinski** [comment]
hey @theramis 

Thank you very much for implementing it so quickly, well done!

I've just put a comment on this but it's more of a preference rather than anything related to the implementation itself.

Yes, I can confirm that's what I was after. Could you merge it and release new version please?

**Comment by theramis** [comment]
Fixed in PR https://github.com/theramis/Snapper/pull/45
Will be released as part of v2.2.1 in the next 20 mins 😄

**Comment by theramis** [comment]
@all-contributors please add @plitwinski  for bugs

**Comment by plitwinski** [comment]
Fantastic, thank you very much!
