### ISSUE TITLE
[DOCUMENTATION] SupportedTestMethodNotFoundException

### ISSUE THREAD

**Issue by Kaca992** [theramis/Snapper#54]
Second issue here: https://theramis.github.io/Snapper/FAQS.html , states that you can fix the problem if you add the following attribute to your method: MethodImpl(MethodImplOptions.NoInlining).

This didn't work by itself, I had to set DebugType also:

 ```
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>full</DebugType>
 </PropertyGroup>
```

While i had it on pdbonly it didn't work. My project is using .NET 4.7.2 and NUnit 3.12. Maybe just add this as a note, spent half day debugging to get it working :)

**Comment by theramis** [comment]
Hey @Kaca992, 

Did you happen to try the other suggested fix which is to disable optimisation?

```
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
     <Optimize>false</Optimize>
 </PropertyGroup>
```

**Comment by Kaca992** [comment]
I tried that and it worked too. I was more curious about the other option (I also saw some comments here saying that option didnt work)

**Comment by theramis** [comment]
I'll add setting `<DebugType>full</DebugType>` to fix the issue in the docs as well. 
Thanks!
