### ISSUE TITLE
Approach to Environment.NewLine

### ISSUE THREAD

**Issue by jzabroski** [theramis/Snapper#56]
**Is your feature request related to a problem? Please describe.**
It seems as though when one contributor creates a snapshot with Linux, and I create a snapshot with Windows, the snapshots will never be in sync due to different `Environment.NewLine` settings.

**Describe the solution you'd like**
Write snapshots to `/.snapper/linux/**` and `/.snapper/windows/**`

Developers can then use tools like Windows Subsystem for Linux to generate snappers in alternative environments through the use of docker images and volumes.

**Describe alternatives you've considered**
1. Manually fixing Environment.NewLine prior to comparing before and after, but this is error prone.
2. Running tool to convert \r\n to \n
3. Stop (trying to) using Snapper :)

**Comment by theramis** [comment]
Hmmm I'm not sure why this is an issue with the current version of Snapper. 

Snapper compares snapshots by converting it to a `JObject` first and then compares the stored snapshot and the new snapshot. By converting it to `JObject` it should remove all line endings from being a factor. 

Would it be possible for you to create a quick demo of this?

**Comment by jzabroski** [comment]
Perhaps the internal comparison is correct, but it writes out the latest version with change in line endings.

I will see if updating Snapper helps - if there was a previous fix for this please let me know. Thank you.

**Comment by theramis** [comment]
> Perhaps the internal comparison is correct, but it writes out the latest version with change in line endings.

Hmm that is quite odd behaviour. It shouldn't update the file unless there was a difference and update snapshots is set.

> I will see if updating Snapper helps - if there was a previous fix for this please let me know. Thank you.

Not that I can think of. The behaviour as always been this. If the latest version doesn't solve the issue would it be possible for you to make a quick project with this issue?
You could add a test into Snapper and make a PR. The PR build runs on a windows instance so if the test was made using linux the line endings issue should be there. 

Sorry I can't be of more help.

**Comment by jzabroski** [comment]
It makes sense for me to create a repro.  Thanks for your explanation as you march towards improving the docs!

**Comment by jzabroski** [comment]
It makes sense for me to create a repro.  Thanks for your explanation as you march towards improving the docs!

**Comment by jzabroski** [comment]
It makes sense for me to create a repro.  Thanks for your explanation as you march towards improving the docs!

**Comment by theramis** [comment]
Hey @jzabroski, did you end up figuring out the problem was?

**Comment by theramis** [comment]
Closing this issue as its been a couple of months and nothing has come of it.
