### ISSUE TITLE
Add alternative snapshots for decimal values

### ISSUE THREAD

**Issue by Dehalion** [theramis/Snapper#83]
I have a lot of data objects with `decimal` values. These are serialized in the snapshots using the default behavior of C#, which keeps all decimal places even if not necessary.

This results in failed snapshots because `10.0` is not the same as `10.000`, which is just due to a change in calculations. The result should be the same though for my use case because it's the same value for further calculations.

I haven't found any settings to deal with this problem, neither in Snapper nor in Netwonsoft.Json

It would be nice though to have a way to tell Snapper that it should treat these decimal values the same so my snapshot tests are not breaking just because the value 10 can be represented with more than one decimal value.

**Comment by aaron-manning** [comment]
This is an issue for me. keep getting false negatives in CI

On one build 10.1 is 10.1, the next it's 10.10

Haven't found a solution yet other than to convert the value to a string before snapshotting

**Comment by theramis** [comment]
Hey @Dehalion and @aaron-manning , 

Just added Custom Snapshot Settings in the latest version [2.4.0](https://www.nuget.org/packages/Snapper/2.4.0). See the docs [here](https://theramis.github.io/Snapper/#/pages/snapper/custom_snapshot_settings). 

You should be able to customise Newtonsoft as you like to make sure this isn't an issue. 
That should hopefully solve your issue?

**Comment by DavidInterad** [comment]
Yes, I already updated and configured the serializer as I need it. Works great.

For anyone interested in the same:
My solution was to create a decimal serializer which keeps only the first decimal to keep the info that it is a decimal number and not an integer (e.g. `1.0` instead of `1`)
```csharp
    public class DecimalJsonConverter : JsonConverter<decimal>
    {
        public override decimal ReadJson(
            JsonReader reader, Type objectType, decimal existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
        public override void WriteJson(JsonWriter writer, decimal value, JsonSerializer serializer)
        {
            // Customise how you want the decimal value to be output in here
            // for example, you may want to consider culture
            writer.WriteRawValue(value.ToString("0.0##############", CultureInfo.InvariantCulture));
        }
    }
```

and then set it before any tests using this code here (I'm using MsTest on this project):
```csharp
    [TestClass]
    public static class TestInitialize
    {
        [AssemblyInitialize]
        public static void BeforeAllTests(TestContext testContext)
        {
            SnapshotSettings.GlobalSnapshotSerialiserSettings = s =>
            {
                s.Converters.Add(new CerFin.TestHelpers.DecimalJsonConverter());
            };
        }
    }
```

**Comment by theramis** [comment]
Closing as its been a while with no response.
