### ISSUE TITLE
Serializing non json values

### ISSUE THREAD

**Issue by WarrenFerrell** [theramis/Snapper#84]
Started using Mongo and considering refactoring some manually written queries to Linq But I want to show that the queries don't change after being refactored. The issue is that the default mongo syntax is not valid json.

Example:
I want to show that the following linq produces the below existing query
```
from u in userCollection
where u.Id == ctx.UserId && u.CustomerId == ctx.CustomerId && u.IsDeleted == false 
select new { _id = 0, UserId = u.Id, u.Email }
```
```
[
        {
            $match : { 
                'CustomerId' : ObjectId("000000000000000000000001"), 
                '_id' : ObjectId("000000000000000000000001"),
                'IsDeleted': false
            }
        },
        { 
            $project : { 
                _id : 0,
                UserId: '$_id', 
                Email : '$Email'
            }
        }
    ]
```

and as it turns out, it does, but if you try to match that string with `command.ShouldMatchSnapshot()` you get a MalformedJsonSnapshotException from the ObjectId line. So you need to do `new { command }.ShouldMatchSnapshot()`
Which will create a snapshot which is not human readable
``` json
{"command":"{\n  \u0022aggregate\u0022 : \u0022User\u0022,\n  \u0022pipeline\u0022 : [{\n      \u0022$match\u0022 : {\n        \u0022_id\u0022 : ObjectId(\u0022000000000000000000000001\u0022),\n        \u0022CustomerId\u0022 : ObjectId(\u0022000000000000000000000001\u0022),\n        \u0022IsDeleted\u0022 : false\n      }\n    }, {\n      \u0022$project\u0022 : {\n        \u0022_id\u0022 : 0,\n        \u0022UserId\u0022 : \u0022$_id\u0022,\n        \u0022Email\u0022 : \u0022$Email\u0022\n      }\n    }],\n  \u0022cursor\u0022 : { },\n  \u0022$db\u0022 : \u0022Data\u0022\n}"}
```

Yaml serialization though produces the following human readable result 
``` yaml
command: >-
  {
    "aggregate" : "User",
    "pipeline" : [{
        "$match" : {
          "_id" : ObjectId("000000000000000000000001"),
          "CustomerId" : ObjectId("000000000000000000000001"),
          "IsDeleted" : false
        }
      }, {
        "$project" : {
          "_id" : 0,
          "UserId" : "$_id",
          "Email" : "$Email"
        }
      }],
    "cursor" : { },
    "$db" : "Data"
  }
```

I think the best solution is to expose ISnapshotStore via an attribute so that users can specify any serialization type they want. Don't mind doing the work but wanted to get people's thoughts first.

Would also serve as a solution to https://github.com/theramis/Snapper/issues/79
, https://github.com/theramis/Snapper/issues/83

**Comment by theramis** [comment]
Hey @WarrenFerrell this isn't the exact fix you wanted but I just released Custom Snapshot Settings in the latest version [2.4.0](https://www.nuget.org/packages/Snapper/2.4.0). See the docs [here](https://theramis.github.io/Snapper/#/pages/snapper/custom_snapshot_settings). 

You could create custom converters to make it easier to serialise/deserialise the objects. 
That should hopefully solve your issue?

**Comment by WarrenFerrell** [comment]
Thanks. I'm not actually working in the .net space anymore (at Amazon) but
yes I think this will solve the problem.
