### ISSUE TITLE
Snapshot created with different serialization settings

### ISSUE THREAD

**Issue by albertomartinsanchez** [theramis/Snapper#89]
**Describe the bug**
When storing snapshots, global settings for NewtonSoft are partially used. Snapper settings should be used instead.

There was a refactor in `Snapper` that fixed issues with dates and times. However, it missed one line (see image attached):

![image](https://user-images.githubusercontent.com/4971812/168528640-d9996bea-5808-4fde-8bd7-c643bd3bcf6d.png)

This is affecting our app, as it is creating invalid snapshots. Could you please fix it for next release?

**To Reproduce**
Just create a new snapshot with two children (aka: 1 file with two "child" snapshots in it), each of them containing a datetime value. Set global settings different from the ones in JObject.Helper. Create the first snapshot (which should be fine), then create the second (which should be also fine), but this operation forces the already created one to be serialized using the global settings, corrupting it.

**Additional context**
Snapper Version: 2.3.1
Operation System: Windows 10
.Net Version: 6.0

**Comment by albertomartinsanchez** [comment]
This is the refactor I'm talking about => https://github.com/theramis/Snapper/pull/45.

Thanks, by the way. And great library, very helpful!

**Comment by theramis** [comment]
Thanks for the bug report and the amazing amount of detail and investigation you did!

I'll make a new release with the fix ASAP!
Gimme an hour or so!

**Comment by theramis** [comment]
The fixed has been pushed out in [v2.3.2](https://www.nuget.org/packages/Snapper/2.3.2)!

Thanks heaps for your bug report!

**Comment by theramis** [comment]
https://github.com/all-contributors please add @albertomartinsanchez  for bugs

**Comment by theramis** [comment]
@all-contributors please add @albertomartinsanchez  for bugs
