### ISSUE TITLE
Support NExpect

### ISSUE THREAD

**Issue by viceice** [theramis/Snapper#94]
**Is your feature request related to a problem? Please describe.**
I like to use snapshot with the `NExpect`[^1] framework.

**Describe the solution you'd like**
Add a new library to support `NExpect` like `NUnit` and others

**Describe alternatives you've considered**
Manual write the wrapper for multiple projects.

**Additional context**

[^1]: https://github.com/fluffynuts/NExpect

**Comment by theramis** [comment]
Hey @viceice, thanks for this. 
Let me have a look at the NExpect library and see what changes I'd need to support it. 
I should have an answer for you in the next 2 days.

**Comment by theramis** [comment]
I made a PR with all the changes. 
Thoughts on the final result?

Best file to look at in the PR is this. It shows how it would look in a real test. 
https://github.com/theramis/Snapper/pull/97/files#diff-a44e9ce892414a99f5f4e618c560e5d7fd3249d6a09a057b9312af1834bf91e1

**Comment by theramis** [comment]
Still todo in other PRs. 

- [ ] Update + Add documentation about the new library
- [ ] Update Changelog + Release the new library

I'd say the ETA for the all above is sometime in the next 7 days.

**Comment by theramis** [comment]
Looks like I can't publish my package until NExpect has been strongly named. 
<img width="893" alt="image" src="https://user-images.githubusercontent.com/5621207/187020494-8153a729-0d3b-4c3f-805c-84ef7a5223a2.png">

**Comment by viceice** [comment]
PR looks promising ❤️

**Comment by theramis** [comment]
unfortunately there is nothing I can do to make it work. 
NExpect would have to be strongly named for me to add Snapper support to it. 

You could add snapper support to it yourself in your test project by essentially adding this file in your test project. 
https://github.com/theramis/Snapper/pull/97/files#diff-7318f8ab372f59b7134758a880e342b2c9e127bd2254600e42ee52ad3138bf1f

Since you won't have access to snapper internals you can do something hacky like this for the `MatchSnapshotMatcher` methods. 

```csharp
private static IMatcherResult MatchSnapshotMatcher<T>(T obj)
{
    var passed = true;
    var message = string.Empty;

    try
    {
        obj.ShouldMatchSnapshot();
    }
    catch (Exception ex)
    {
        passed = false;
        message = ex.Message;
    }
    
    return new MatcherResult(passed, message);
}
```

**Comment by viceice** [comment]
OK, using this:

```cs
internal static class NExpectExtensions
{
    public static void MatchChildSnapshot<T>(this ITo<T> to, string childSnapshotName)
    {
        to.AddMatcher(obj =>
        {
            var passed = true;
            var message = string.Empty;

            try
            {
                obj.ShouldMatchChildSnapshot(childSnapshotName);
            }
            catch (Exception ex)
            {
                passed = false;
                message = ex.Message;
            }

            return new MatcherResult(passed, message);
        });
    }

    public static void MatchSnapshot<T>(this ITo<T> to)
    {
        to.AddMatcher(obj =>
        {
            var passed = true;
            var message = string.Empty;

            try
            {
                obj.ShouldMatchSnapshot();
            }
            catch (Exception ex)
            {
                passed = false;
                message = ex.Message;
            }

            return new MatcherResult(passed, message);
        });
    }
}

Expect(doc).To.MatchSnapshot();
```


Would be nice to use `Expect(doc).To.Match.Snapshot();` 🙃

**Comment by viceice** [comment]
What is the `localExeption` parameter of the `MatcherResult` used for?

```cs
 public static void MatchSnapshot<T>(this ITo<T> to)
 {
     to.AddMatcher(obj =>
     {
         try
         {
             obj.ShouldMatchSnapshot();
             return new MatcherResult(true);
         }
         catch (Exception ex)
         {
             return new MatcherResult(false, () => ex.Message, ex);
         }
     });
 }
```

**Comment by theramis** [comment]
> Would be nice to use `Expect(doc).To.Match.Snapshot();` 🙃

You could do that but you'd have to implement your own Match object. Kinda like how `To` was done here https://github.com/fluffynuts/NExpect/blob/master/src/NExpect/Implementations/Fluency/To.cs. (although maybe for Match you only want to allow Snapshot after but that depends on how much functionality should be allowed after the Match keyword.)

You could ask the NExpect owner to add that in if you'd like that?


> What is the `localExeption` parameter of the `MatcherResult` used for?
> 
> ```cs
>  public static void MatchSnapshot<T>(this ITo<T> to)
>  {
>      to.AddMatcher(obj =>
>      {
>          try
>          {
>              obj.ShouldMatchSnapshot();
>              return new MatcherResult(true);
>          }
>          catch (Exception ex)
>          {
>              return new MatcherResult(false, () => ex.Message, ex);
>          }
>      });
>  }
> ```

The docs say it's used when using `.Throw()` https://github.com/fluffynuts/NExpect/blob/master/src/NExpect/MatcherLogic/IMatcherResult.cs#L26-L30
