### ISSUE TITLE
Support for Unity Test Framework

### ISSUE THREAD

**Issue by ques-vehikl** [theramis/Snapper#95]
Our team is currently trying to adopt Snapper in a Unity project, but there is no support for the Unity Test Framework.

**Comment by theramis** [comment]
Hey @ques-vehikl, 

Would you be interested in contributing and adding support support for it?
There are instructions here https://theramis.github.io/Snapper/#/pages/supported_test_frameworks?id=how-to-add-support-for-a-new-test-framework if you are keen?

**Comment by ques-vehikl** [comment]
For sure, will keep you posted here if our team has any questions

**Comment by theramis** [comment]
awesome, looking forward to your PR!

**Comment by JoC0de** [comment]
Unity Test Framework is compatible with / uses NUnit so i see no reason why you shouldn't be able to use it in Unity. But I didn't test it. So just importing the NuGet package using NugetForUnity should work.

**Comment by theramis** [comment]
Closing as its been a while with no response.
