### ISSUE TITLE
Remove support for .net 45

### ISSUE THREAD

**Issue by theramis** [theramis/Snapper#98]
## Background 
Snapper and Snapper.NUnit both currently support `.NET framework 4.5`. 
.net 45 is officially end of life by Microsoft (as of 4 months ago) and no more updates (security or feature updates) will be provided. 
See https://endoflife.date/dotnetfx

## Problem
A few of the other nuget packages which the Snapper solution uses have been updated and they do not support .net 45 anymore. It's likely that all of the other nuget packages will be following suit. 
This means that Snapper cannot update its dependencies. 

## Suggested solution 
Drop support for .net 45. 
The oldest .net framework that is still supported is .net 462 and since Snapper already support .net standard 2.0, it is already compatible with .net 462.

**Comment by theramis** [comment]
@viceice I know you originally wanted support for .net 45. 
Thought I'd give you a heads up about this.

**Comment by viceice** [comment]
that's fine, we no longer use net45. we are on 472 as minimal version now. 🤗

**Comment by theramis** [comment]
Removed support for .net45 in the latest version [v2.4.0](https://www.nuget.org/packages/Snapper/2.4.0)
